// Shared PIN -> locality map (extracted from report page).
export const PIN_META = {
  // 110001 and 121102 were scored in nqi_scores.json but had no entry
  // here, so the picker showed the raw pincode where every other locality
  // shows a name. Same class of gap as a missing AREA_COORDS entry, just
  // less severe (that one produces a dead end rather than an ugly label).
  "110001":{ name:"Connaught Place",   area:"Central Delhi" },
  "110002":{ name:"ITO",               area:"Central Delhi" },
  "110003":{ name:"Lodhi Road",        area:"South Delhi" },
  "110005":{ name:"Karol Bagh",        area:"Central Delhi" },
  "110006":{ name:"Chandni Chowk",     area:"Old Delhi" },
  "110007":{ name:"Delhi University",  area:"North Delhi" },
  "110008":{ name:"Shadipur",          area:"West Delhi" },
  "110009":{ name:"Model Town",        area:"North Delhi" },
  "110010":{ name:"Cantonment",        area:"South Delhi" },
  "110012":{ name:"Pusa",              area:"Central Delhi" },
  "110016":{ name:"Hauz Khas",         area:"South Delhi" },
  "110017":{ name:"Saket",             area:"South Delhi" },
  "110018":{ name:"Vikaspuri",         area:"West Delhi" },
  "110019":{ name:"Dwarka Sec 6",      area:"South West Delhi" },
  "110020":{ name:"Okhla",             area:"South East Delhi" },
  "110021":{ name:"Moti Bagh",         area:"South Delhi" },
  "110022":{ name:"R.K. Puram",        area:"South West Delhi" },
  "110024":{ name:"Lajpat Nagar",      area:"South Delhi" },
  "110025":{ name:"Mathura Road",      area:"South Delhi" },
  "110026":{ name:"Punjabi Bagh",      area:"West Delhi" },
  "110032":{ name:"Anand Vihar",       area:"East Delhi" },
  "110033":{ name:"Jahangirpuri",      area:"North West Delhi" },
  "110034":{ name:"Pitampura",         area:"North West Delhi" },
  "110036":{ name:"Alipur",            area:"North Delhi" },
  "110037":{ name:"Aerocity",          area:"South West Delhi" },
  "110039":{ name:"Bawana",            area:"North Delhi" },
  "110040":{ name:"Narela",            area:"North Delhi" },
  "110041":{ name:"Mundka",            area:"West Delhi" },
  "110042":{ name:"DTU",               area:"North West Delhi" },
  "110043":{ name:"Najafgarh",         area:"South West Delhi" },
  "110044":{ name:"Tughlakabad",       area:"South Delhi" },
  "110049":{ name:"Sirifort",          area:"South Delhi" },
  "110052":{ name:"Ashok Vihar",       area:"North Delhi" },
  "110053":{ name:"Maujpur",           area:"North East Delhi" },
  "110058":{ name:"Janakpuri",         area:"West Delhi" },
  "110063":{ name:"Paschim Vihar",     area:"West Delhi" },
  "110065":{ name:"Nehru Nagar",       area:"East Delhi" },
  "110067":{ name:"JNU Area",          area:"South Delhi" },
  "110068":{ name:"Maidan Garhi",      area:"South Delhi" },
  "110070":{ name:"Vasant Kunj",       area:"South West Delhi" },
  "110073":{ name:"Jaffarpur",         area:"West Delhi" },
  "110077":{ name:"Dwarka Sec 8",      area:"South West Delhi" },
  "110078":{ name:"Dwarka",            area:"South West Delhi" },
  "110084":{ name:"Burari",            area:"North Delhi" },
  "110085":{ name:"Rohini",            area:"North West Delhi" },
  "110091":{ name:"Mayur Vihar",       area:"East Delhi" },
  "110092":{ name:"Patparganj",        area:"East Delhi" },
  "110094":{ name:"Sonia Vihar",       area:"North East Delhi" },
  "110095":{ name:"Vivek Vihar",       area:"East Delhi" },
  "121001":{ name:"Faridabad",         area:"Haryana NCR" },
  "121102":{ name:"Ballabgarh",        area:"Haryana NCR" },
  "121002":{ name:"Faridabad NIT",     area:"Haryana NCR" },
  "122001":{ name:"Gurugram",          area:"Haryana NCR" },
  "122002":{ name:"Cyber City",        area:"Gurugram" },
  "122003":{ name:"Gurugram Sec 55",   area:"Gurugram" },
  "122051":{ name:"Manesar",           area:"Gurugram" },
  "122107":{ name:"Nuh",               area:"Haryana NCR" },
  "122413":{ name:"Panchgaon",         area:"Gurugram" },
  "123106":{ name:"Dharuhera",         area:"Haryana NCR" },
  "124001":{ name:"Rohtak",            area:"Haryana NCR" },
  "124507":{ name:"Bahadurgarh",       area:"Haryana NCR" },
  "125050":{ name:"Fatehabad",         area:"Haryana NCR" },
  "125055":{ name:"Sirsa",             area:"Haryana NCR" },
  "131001":{ name:"Sonipat",           area:"Haryana NCR" },
  "132103":{ name:"Panipat",           area:"Haryana NCR" },
  "135001":{ name:"Yamuna Nagar",      area:"Haryana NCR" },
  "201001":{ name:"Ghaziabad",         area:"UP NCR" },
  "201301":{ name:"Noida Sec 1",       area:"UP NCR" },
  "201304":{ name:"Noida Sec 137",     area:"UP NCR" },
  "201309":{ name:"Noida Sec 62",      area:"UP NCR" },
  // NCR fringe — in our coverage zone but no data yet
  "122505":{ name:"Mahendragarh",      area:"Haryana NCR" },
  "122502":{ name:"Rewari",            area:"Haryana NCR" },
  "122108":{ name:"Taoru",             area:"Haryana NCR" },
  "122101":{ name:"Sohna",             area:"Haryana NCR" },
  "122103":{ name:"Gurgaon South",     area:"Haryana NCR" },
  "123001":{ name:"Jhajjar",           area:"Haryana NCR" },
  "123401":{ name:"Rewari Town",       area:"Haryana NCR" },
  "131029":{ name:"Kundli",            area:"Haryana NCR" },
  "131027":{ name:"Murthal",           area:"Haryana NCR" },
  "201102":{ name:"Loni",              area:"UP NCR" },
  "201014":{ name:"Indirapuram",       area:"UP NCR" },
  "201012":{ name:"Vasundhara",        area:"UP NCR" },
  "201016":{ name:"Crossing Republik", area:"UP NCR" },
  "201002":{ name:"Raj Nagar",         area:"UP NCR" },
  "201010":{ name:"Kaushambi",         area:"UP NCR" },
  "201206":{ name:"Muradnagar",        area:"UP NCR" },
  "245101":{ name:"Hapur",             area:"UP NCR" },
  "203001":{ name:"Bulandshahr",       area:"UP NCR" },
  // ── Bengaluru (city 2) ──
  "560001":{ name:"MG Road", area:"Central Bengaluru", city:"Bangalore" },
  "560025":{ name:"Richmond Town", area:"Central Bengaluru", city:"Bangalore" },
  "560051":{ name:"HKP Road", area:"Central Bengaluru", city:"Bangalore" },
  "560052":{ name:"Vasanth Nagar", area:"Central Bengaluru", city:"Bangalore" },
  "560042":{ name:"Shivajinagar", area:"Central Bengaluru", city:"Bangalore" },
  "560002":{ name:"Chickpet", area:"Central Bengaluru", city:"Bangalore" },
  "560023":{ name:"Majestic", area:"Central Bengaluru", city:"Bangalore" },
  "560003":{ name:"Malleshwaram", area:"North Bengaluru", city:"Bangalore" },
  "560010":{ name:"Rajajinagar", area:"North Bengaluru", city:"Bangalore" },
  "560020":{ name:"Seshadripuram", area:"North Bengaluru", city:"Bangalore" },
  "560021":{ name:"Sriramapuram", area:"North Bengaluru", city:"Bangalore" },
  "560022":{ name:"Yeshwanthpur", area:"North Bengaluru", city:"Bangalore" },
  "560024":{ name:"Hebbal", area:"North Bengaluru", city:"Bangalore" },
  "560032":{ name:"RT Nagar", area:"North Bengaluru", city:"Bangalore" },
  "560045":{ name:"Nagavara", area:"North Bengaluru", city:"Bangalore" },
  "560092":{ name:"Vidyaranyapura", area:"North Bengaluru", city:"Bangalore" },
  "560094":{ name:"Sanjaynagar", area:"North Bengaluru", city:"Bangalore" },
  "560097":{ name:"Byatarayanapura", area:"North Bengaluru", city:"Bangalore" },
  "560063":{ name:"Yelahanka", area:"North Bengaluru", city:"Bangalore" },
  "560064":{ name:"Yelahanka New Town", area:"North Bengaluru", city:"Bangalore" },
  "560065":{ name:"Jakkur", area:"North Bengaluru", city:"Bangalore" },
  "560008":{ name:"Ulsoor", area:"East Bengaluru", city:"Bangalore" },
  "560038":{ name:"Indiranagar East", area:"East Bengaluru", city:"Bangalore" },
  "560046":{ name:"Benson Town", area:"East Bengaluru", city:"Bangalore" },
  "560005":{ name:"Cox Town", area:"East Bengaluru", city:"Bangalore" },
  "560017":{ name:"HAL / Old Airport", area:"East Bengaluru", city:"Bangalore" },
  "560075":{ name:"New Thippasandra", area:"East Bengaluru", city:"Bangalore" },
  "560093":{ name:"CV Raman Nagar", area:"East Bengaluru", city:"Bangalore" },
  "560016":{ name:"Ramamurthy Nagar", area:"East Bengaluru", city:"Bangalore" },
  "560036":{ name:"KR Puram", area:"East Bengaluru", city:"Bangalore" },
  "560037":{ name:"Marathahalli", area:"East Bengaluru", city:"Bangalore" },
  "560048":{ name:"Mahadevapura", area:"East Bengaluru", city:"Bangalore" },
  "560066":{ name:"Whitefield", area:"East Bengaluru", city:"Bangalore" },
  "560067":{ name:"Whitefield Hope Farm", area:"East Bengaluru", city:"Bangalore" },
  "560103":{ name:"Bellandur", area:"East Bengaluru", city:"Bangalore" },
  "560035":{ name:"Sarjapur Road", area:"East Bengaluru", city:"Bangalore" },
  "560087":{ name:"Varthur", area:"East Bengaluru", city:"Bangalore" },
  "560034":{ name:"Koramangala", area:"South East Bengaluru", city:"Bangalore" },
  "560095":{ name:"Koramangala 8th Blk", area:"South East Bengaluru", city:"Bangalore" },
  "560102":{ name:"HSR Layout", area:"South East Bengaluru", city:"Bangalore" },
  "560029":{ name:"Adugodi", area:"South East Bengaluru", city:"Bangalore" },
  "560027":{ name:"Shanti Nagar", area:"South East Bengaluru", city:"Bangalore" },
  "560030":{ name:"Wilson Garden", area:"South East Bengaluru", city:"Bangalore" },
  "560068":{ name:"Bommanahalli", area:"South East Bengaluru", city:"Bangalore" },
  "560004":{ name:"Basavanagudi", area:"South Bengaluru", city:"Bangalore" },
  "560011":{ name:"Jayanagar", area:"South Bengaluru", city:"Bangalore" },
  "560041":{ name:"Jayanagar 4th Block", area:"South Bengaluru", city:"Bangalore" },
  "560019":{ name:"Hanumanthanagar", area:"South Bengaluru", city:"Bangalore" },
  "560028":{ name:"Tyagarajanagar", area:"South Bengaluru", city:"Bangalore" },
  "560050":{ name:"Banashankari", area:"South Bengaluru", city:"Bangalore" },
  "560070":{ name:"BSK 2nd Stage", area:"South Bengaluru", city:"Bangalore" },
  "560085":{ name:"BSK 3rd Stage", area:"South Bengaluru", city:"Bangalore" },
  "560078":{ name:"JP Nagar", area:"South Bengaluru", city:"Bangalore" },
  "560076":{ name:"BTM Layout", area:"South Bengaluru", city:"Bangalore" },
  "560061":{ name:"Uttarahalli", area:"South Bengaluru", city:"Bangalore" },
  "560062":{ name:"Konanakunte", area:"South Bengaluru", city:"Bangalore" },
  "560083":{ name:"Bannerghatta Road", area:"South Bengaluru", city:"Bangalore" },
  "560040":{ name:"Vijayanagar", area:"West Bengaluru", city:"Bangalore" },
  "560079":{ name:"Basaveshwaranagar", area:"West Bengaluru", city:"Bangalore" },
  "560072":{ name:"Nagarbhavi", area:"West Bengaluru", city:"Bangalore" },
  "560018":{ name:"Chamrajpet", area:"West Bengaluru", city:"Bangalore" },
  "560091":{ name:"Sunkadakatte", area:"West Bengaluru", city:"Bangalore" },
  "560056":{ name:"Jnana Bharathi", area:"West Bengaluru", city:"Bangalore" },
  "560100":{ name:"Electronic City", area:"South Bengaluru", city:"Bangalore" },
  "560099":{ name:"Hosur Road", area:"South Bengaluru", city:"Bangalore" },
  "560105":{ name:"Anekal", area:"South Bengaluru", city:"Bangalore" },

  // ── Chandigarh (city 3) — every sector 1-56 (no 13) + villages.
  //    `sectors` drives search ('Sector 50' must find its pincode even
  //    though the name only shows a range); `aliases` are landmarks.
  "160001":{ name:"Sectors 1-5 · Capitol Complex", area:"North Chandigarh", city:"Chandigarh", sectors:[1,2,3,4,5], aliases:["Capitol Complex","High Court","New Secretariat","Rajendra Park"] },
  "160009":{ name:"Sectors 8-9", area:"North Chandigarh", city:"Chandigarh", sectors:[8,9], aliases:["UT Secretariat"] },
  "160011":{ name:"Sectors 10-11", area:"North Chandigarh", city:"Chandigarh", sectors:[10,11] },
  "160012":{ name:"Sector 12 · PEC", area:"North Chandigarh", city:"Chandigarh", sectors:[12], aliases:["PEC","Punjab Engineering College"] },
  "160014":{ name:"Sector 14 · Panjab University", area:"West Chandigarh", city:"Chandigarh", sectors:[14,24,25], aliases:["Panjab University","PU","Dadu Majra","Dhanas","Khuda Lahora","Khuda Jassu","Khuda Alisher","Kaimbwala","Sarangpur"] },
  "160015":{ name:"Sectors 15-16", area:"Central Chandigarh", city:"Chandigarh", sectors:[15,16] },
  "160017":{ name:"Sector 17 · City Centre", area:"Central Chandigarh", city:"Chandigarh", sectors:[17], aliases:["GPO","City Centre","Bus Stand 17","ISBT 17"] },
  "160018":{ name:"Sector 18", area:"Central Chandigarh", city:"Chandigarh", sectors:[18], aliases:["Government Press"] },
  "160019":{ name:"Sectors 6-7, 19, 26-27", area:"East Chandigarh", city:"Chandigarh", sectors:[6,7,19,26,27], aliases:["Raj Bhawan","Grain Market"] },
  "160020":{ name:"Sector 20", area:"Central Chandigarh", city:"Chandigarh", sectors:[20] },
  "160022":{ name:"Sectors 21-22, 32-35", area:"Central Chandigarh", city:"Chandigarh", sectors:[21,22,32,33,34,35], aliases:["Sub City Centre","GMCH 32","PGI"] },
  "160023":{ name:"Sector 23", area:"Central Chandigarh", city:"Chandigarh", sectors:[23,28] },
  "160025":{ name:"Maloya · Sector 39", area:"West Chandigarh", city:"Chandigarh", sectors:[39], aliases:["Maloya","Milk Colony"] },
  "160030":{ name:"Sectors 29-31", area:"East Chandigarh", city:"Chandigarh", sectors:[29,30,31] },
  "160036":{ name:"Sectors 36-38, 40-43", area:"South Chandigarh", city:"Chandigarh", sectors:[36,37,38,40,41,42,43], aliases:["ISBT 43","Bus Stand 43","Attawa","Badheri","Buterla"] },
  "160047":{ name:"Sectors 44-56", area:"South Chandigarh", city:"Chandigarh", sectors:[44,45,46,47,48,49,50,51,52,53,54,55,56], aliases:["Burail","Kajheri","Palsora"] },
  "160002":{ name:"Ram Darbar · Industrial Area", area:"South-East Chandigarh", city:"Chandigarh", aliases:["Ram Darbar","Industrial Area Phase 1","Industrial Area Phase 2","Elante","Nexus Elante","IT Park","Rajiv Gandhi IT Park"] },
  "160004":{ name:"Air Force Station · Highground", area:"South-East Chandigarh", city:"Chandigarh", aliases:["Airforce Highground","Air Force Station"] },
  "160101":{ name:"Manimajra", area:"East Chandigarh", city:"Chandigarh", aliases:["Manimajra","Mani Majra","Motor Market","Shivalik Enclave","Modern Housing Complex"] },
  "160102":{ name:"Mauli Jagran · Raipur Kalan", area:"North-East Chandigarh", city:"Chandigarh", aliases:["Mauli Jagran","Raipur Kalan","Raipur Khurd","Behlana","Daria","Hallomajra"] },

  // ── Mumbai (city 4) — Greater Mumbai / BMC jurisdiction, 94 pincodes.
  "400001":{ name:"Fort / CSMT / Churchgate East", area:"A Ward", city:"Mumbai", aliases:["Gateway of India","CST/VT Terminus","BSE","Town Hall","Bazargate"] },
  "400002":{ name:"Kalbadevi", area:"C Ward", city:"Mumbai", aliases:["Zaveri Bazaar","Mumbadevi Temple"] },
  "400003":{ name:"Mandvi / Masjid Bunder", area:"B Ward", city:"Mumbai", aliases:["Crawford Market"] },
  "400004":{ name:"Girgaon / Chowpatty", area:"C/D Ward", city:"Mumbai", aliases:["Girgaon Chowpatty","Opera House"] },
  "400005":{ name:"Colaba", area:"A Ward", city:"Mumbai", aliases:["Gateway of India","Taj Mahal Palace","Colaba Causeway"] },
  "400006":{ name:"Malabar Hill", area:"D Ward", city:"Mumbai", aliases:["Hanging Gardens","Banganga Tank"] },
  "400007":{ name:"Grant Road / Tardeo", area:"D Ward", city:"Mumbai", aliases:["Grant Road Station"] },
  "400008":{ name:"Mumbai Central", area:"D/E Ward", city:"Mumbai", aliases:["Mumbai Central Terminus","JJ Hospital"] },
  "400009":{ name:"Chinch Bunder / Byculla East", area:"B Ward", city:"Mumbai" },
  "400010":{ name:"Mazgaon", area:"B Ward", city:"Mumbai", aliases:["Mazagon Dock Shipbuilders"] },
  "400011":{ name:"Jacob Circle / Agripada", area:"E Ward", city:"Mumbai" },
  "400012":{ name:"Parel / Lalbaug", area:"F/South Ward", city:"Mumbai", aliases:["Lalbaugcha Raja","Haffkine Institute"] },
  "400013":{ name:"Lower Parel", area:"G/South Ward", city:"Mumbai", aliases:["Phoenix Mills / High Street Phoenix","Kamala Mills"] },
  "400014":{ name:"Dadar East / Naigaon", area:"F/S · G/N Ward", city:"Mumbai", aliases:["Dadar TT"] },
  "400015":{ name:"Sewri", area:"F/South Ward", city:"Mumbai", aliases:["Sewri Fort (flamingo point)"] },
  "400016":{ name:"Mahim", area:"G/North Ward", city:"Mumbai", aliases:["Mahim Dargah","Mahim Causeway"] },
  "400017":{ name:"Dharavi", area:"G/North Ward", city:"Mumbai", aliases:["Dharavi"] },
  "400018":{ name:"Worli", area:"G/South Ward", city:"Mumbai", aliases:["Worli Sea Face","NSCI Dome","Atria Mall"] },
  "400019":{ name:"Matunga", area:"F/North Ward", city:"Mumbai", aliases:["Matunga Railway Workshop","Five Gardens"] },
  "400020":{ name:"Churchgate / Marine Lines", area:"A Ward", city:"Mumbai", aliases:["Churchgate Station","Marine Drive"] },
  "400021":{ name:"Nariman Point", area:"A Ward", city:"Mumbai", aliases:["Nariman Point business district"] },
  "400022":{ name:"Sion", area:"F/North Ward", city:"Mumbai", aliases:["Sion Fort","Sion Hospital"] },
  "400023":{ name:"Hutatma Chowk (Fort)", area:"A Ward", city:"Mumbai", aliases:["Flora Fountain"] },
  "400024":{ name:"Kurla East / Nehru Nagar", area:"L Ward", city:"Mumbai", aliases:["Nehru Nagar"] },
  "400025":{ name:"Prabhadevi", area:"G/North Ward", city:"Mumbai", aliases:["Siddhivinayak Temple"] },
  "400026":{ name:"Cumballa Hill / Kemps Corner", area:"D Ward", city:"Mumbai", aliases:["Kemps Corner","August Kranti Maidan"] },
  "400027":{ name:"Byculla (Rani Baug)", area:"E Ward", city:"Mumbai", aliases:["Rani Baug / Byculla Zoo","Bhau Daji Lad Museum"] },
  "400028":{ name:"Dadar West / Shivaji Park", area:"G/North Ward", city:"Mumbai", aliases:["Shivaji Park"] },
  "400029":{ name:"Kalina / Vakola", area:"H/East Ward", city:"Mumbai", aliases:["Santacruz P&T Colony"] },
  "400030":{ name:"Worli Colony", area:"G/South Ward", city:"Mumbai" },
  "400031":{ name:"Wadala", area:"F/North Ward", city:"Mumbai", aliases:["Wadala Truck Terminal"] },
  "400032":{ name:"Mantralaya", area:"A Ward", city:"Mumbai", aliases:["Mantralaya","Vidhan Bhavan"] },
  "400033":{ name:"Cotton Green / Kalachowki", area:"E Ward", city:"Mumbai", aliases:["Cotton Exchange Building"] },
  "400034":{ name:"Haji Ali / Mahalaxmi", area:"D Ward", city:"Mumbai", aliases:["Haji Ali Dargah","Mahalaxmi Racecourse"] },
  "400035":{ name:"Raj Bhavan (Malabar Point)", area:"D Ward", city:"Mumbai", aliases:["Raj Bhavan"] },
  "400036":{ name:"August Kranti Marg", area:"D Ward", city:"Mumbai" },
  "400037":{ name:"Antop Hill", area:"F/North Ward", city:"Mumbai" },
  "400038":{ name:"Ballard Estate", area:"A Ward", city:"Mumbai", aliases:["Ballard Estate","Mumbai Port Trust"] },
  "400039":{ name:"Council Hall (Fort)", area:"A Ward", city:"Mumbai" },
  "400049":{ name:"Juhu", area:"K/West Ward", city:"Mumbai", aliases:["Juhu Beach","ISKCON Temple","Prithvi Theatre"] },
  "400050":{ name:"Bandra West", area:"H/West Ward", city:"Mumbai", aliases:["Bandstand","Mount Mary Church","Linking Road"] },
  "400051":{ name:"Bandra East / BKC", area:"H/East Ward", city:"Mumbai", aliases:["Bandra Kurla Complex","MMRDA Grounds"] },
  "400052":{ name:"Khar", area:"H/West Ward", city:"Mumbai", aliases:["Khar Gymkhana"] },
  "400053":{ name:"Andheri West (Azad Nagar)", area:"K/West Ward", city:"Mumbai", aliases:["Infinity Mall"] },
  "400054":{ name:"Santacruz West", area:"H/West Ward", city:"Mumbai" },
  "400055":{ name:"Santacruz East / Vakola", area:"H/East Ward", city:"Mumbai", aliases:["Domestic Airport environs"] },
  "400056":{ name:"Vile Parle West", area:"H/West Ward", city:"Mumbai" },
  "400057":{ name:"Vile Parle East", area:"K/East Ward", city:"Mumbai", aliases:["NMIMS University"] },
  "400058":{ name:"Andheri West (Lokhandwala)", area:"K/West Ward", city:"Mumbai", aliases:["Lokhandwala Complex","Andheri Station"] },
  "400059":{ name:"Andheri East / Marol", area:"K/East Ward", city:"Mumbai", aliases:["Marol MIDC"] },
  "400060":{ name:"Jogeshwari East", area:"K/East Ward", city:"Mumbai" },
  "400061":{ name:"Versova / Madh", area:"K/West Ward", city:"Mumbai", aliases:["Versova Beach","Madh Island"] },
  "400062":{ name:"Goregaon West", area:"P/South Ward", city:"Mumbai", aliases:["Goregaon Station","Oberoi Mall"] },
  "400063":{ name:"Goregaon East", area:"P/South Ward", city:"Mumbai", aliases:["Film City","NESCO"] },
  "400064":{ name:"Malad West", area:"P/North Ward", city:"Mumbai", aliases:["Malad Station","Inorbit Mall"] },
  "400065":{ name:"Aarey Colony", area:"P/South Ward", city:"Mumbai", aliases:["Aarey Milk Colony","SGNP edge"] },
  "400066":{ name:"Borivali East (Magathane)", area:"R/Central Ward", city:"Mumbai", aliases:["SGNP entrance"] },
  "400067":{ name:"Kandivali West / Charkop", area:"R/South Ward", city:"Mumbai", aliases:["Charkop","Mahavir Nagar"] },
  "400068":{ name:"Dahisar", area:"R/North Ward", city:"Mumbai", aliases:["Dahisar check naka (Mumbai-Thane border)"] },
  "400069":{ name:"Andheri East (Nagardas Rd)", area:"K/East Ward", city:"Mumbai", aliases:["Chakala"] },
  "400090":{ name:"Bangur Nagar (Goregaon W)", area:"P/South Ward", city:"Mumbai" },
  "400091":{ name:"Borivali West", area:"R/North Ward", city:"Mumbai", aliases:["Borivali Station","National Park main gate"] },
  "400092":{ name:"Borivali West (Sundar Nagar)", area:"R/Central Ward", city:"Mumbai" },
  "400093":{ name:"Chakala MIDC (Andheri E)", area:"K/East Ward", city:"Mumbai", aliases:["MIDC Chakala","Airport cargo complex"] },
  "400095":{ name:"Kharodi / INS Hamla", area:"K/West Ward", city:"Mumbai", aliases:["INS Hamla","Madh-Marve"] },
  "400096":{ name:"SEEPZ", area:"K/East Ward", city:"Mumbai", aliases:["SEEPZ Special Economic Zone"] },
  "400097":{ name:"Malad East", area:"P/North Ward", city:"Mumbai", aliases:["Mindspace IT Park vicinity"] },
  "400098":{ name:"Vidyanagari (Kalina)", area:"H/East Ward", city:"Mumbai", aliases:["University of Mumbai Kalina Campus"] },
  "400099":{ name:"Sahar / Airport", area:"K/East Ward", city:"Mumbai", aliases:["Chhatrapati Shivaji Maharaj Int'l Airport"] },
  "400101":{ name:"Kandivali East", area:"R/South Ward", city:"Mumbai", aliases:["Thakur Village"] },
  "400102":{ name:"Jogeshwari West / Oshiwara", area:"K/West Ward", city:"Mumbai", aliases:["Oshiwara"] },
  "400103":{ name:"Mandapeshwar (Borivali W)", area:"R/Central Ward", city:"Mumbai", aliases:["Mandapeshwar Caves"] },
  "400104":{ name:"Motilal Nagar (Goregaon W)", area:"P/South Ward", city:"Mumbai", aliases:["Motilal Nagar"] },
  "400070":{ name:"Kurla West", area:"L Ward", city:"Mumbai", aliases:["Kurla Station","Nehru Nagar"] },
  "400071":{ name:"Chembur", area:"M/West Ward", city:"Mumbai", aliases:["Diamond Garden","Priyadarshini Park"] },
  "400072":{ name:"Saki Naka", area:"L Ward", city:"Mumbai", aliases:["Saki Naka industrial belt"] },
  "400073":{ name:"Trombay", area:"M/West Ward", city:"Mumbai", aliases:["BARC vicinity","Trombay thermal power station"] },
  "400074":{ name:"RCF Chembur / Mahul", area:"M/East-West Ward", city:"Mumbai", aliases:["RCF fertiliser complex","Mahul refineries"] },
  "400075":{ name:"Pant Nagar (Ghatkopar E)", area:"N Ward", city:"Mumbai", aliases:["Pant Nagar"] },
  "400076":{ name:"Powai", area:"L Ward", city:"Mumbai", aliases:["IIT Bombay","Powai Lake","Hiranandani Gardens"] },
  "400077":{ name:"Ghatkopar", area:"N Ward", city:"Mumbai", aliases:["Ghatkopar rail/metro interchange"] },
  "400078":{ name:"Bhandup West", area:"S Ward", city:"Mumbai", aliases:["Bhandup pumping station (BMC waterworks)"] },
  "400079":{ name:"Vikhroli", area:"S/N Ward", city:"Mumbai", aliases:["Godrej & Boyce complex"] },
  "400080":{ name:"Mulund West", area:"T Ward", city:"Mumbai", aliases:["Mulund check naka (Mumbai-Thane border)"] },
  "400081":{ name:"Mulund East", area:"T Ward", city:"Mumbai", aliases:["Nirmal Lifestyle Mall"] },
  "400082":{ name:"Mulund Colony", area:"T Ward", city:"Mumbai" },
  "400083":{ name:"Vikhroli / Tagore Nagar", area:"S Ward", city:"Mumbai", aliases:["Tagore Nagar"] },
  "400084":{ name:"Kurla West (Barve Nagar)", area:"L Ward", city:"Mumbai" },
  "400085":{ name:"BARC / Trombay", area:"M/West Ward", city:"Mumbai", aliases:["Bhabha Atomic Research Centre"] },
  "400094":{ name:"Anushakti Nagar", area:"M/East Ward", city:"Mumbai", aliases:["Anushakti Nagar S.O. (BARC residential colony)","Atomic Energy Education Society"] },
  "400042":{ name:"Bhandup East", area:"S Ward", city:"Mumbai", aliases:["Bhandup Station (Central Line)","Sonapur signal, L.B.S. Marg"] },
  "400086":{ name:"Ghatkopar West (NITIE)", area:"N Ward", city:"Mumbai", aliases:["NITIE"] },
  "400087":{ name:"Vikhroli West", area:"S Ward", city:"Mumbai" },
  "400088":{ name:"Deonar", area:"M/East Ward", city:"Mumbai", aliases:["Deonar abattoir","Deonar dumping ground"] },
  "400089":{ name:"Tilak Nagar (Chembur)", area:"M/West Ward", city:"Mumbai", aliases:["Tilak Nagar Chembur"] },
  "400043":{ name:"Govandi", area:"M/East Ward", city:"Mumbai", aliases:["Govandi","Shivaji Nagar"] },
}
