// app/api/av-lifestyle/route.js
// Reads the pre-fetched lifestyle/nightlife-density data (generated by
// scripts/fetch-lifestyle-scores.mjs, checked in like nqi_scores.json) and
// merges in locality name + centroid, same pattern as av-localities/route.js.
// No live Places API calls happen here -- this just serves the committed
// data file, so it's free and fast on every page load.

import { NextResponse } from 'next/server';
import fs from 'node:fs';
import path from 'node:path';
import { PIN_META } from '@/lib/aslivastu/pinMeta';
import { AREA_COORDS } from '@/lib/aslivastu/areaCoords';

export async function GET() {
  try {
    const filePath = path.join(process.cwd(), 'data', 'aslivastu', 'lifestyle_scores.json');
    if (!fs.existsSync(filePath)) {
      return NextResponse.json(
        { error: 'Lifestyle data not generated yet -- run scripts/fetch-lifestyle-scores.mjs' },
        { status: 404 }
      );
    }
    const scores = JSON.parse(fs.readFileSync(filePath, 'utf8'));

    const byCity = {};
    for (const r of scores) {
      if (r.error) continue; // skip pincodes that failed to fetch
      const meta = PIN_META[r.pin_code];
      const coords = AREA_COORDS[r.pin_code];
      const enriched = {
        pin_code: r.pin_code,
        name: meta?.name || r.pin_code,
        area: meta?.area || null,
        city: r.city,
        lat: coords ? coords[0] : null,
        lon: coords ? coords[1] : null,
        lifestyle_composite: r.lifestyle_composite,
        scores: r.scores,
        nightlife_count: r.nightlife_count,
        dining_count: r.dining_count,
        cafes_count: r.cafes_count,
        top_nightlife: r.top_nightlife || [],
        top_dining: r.top_dining || [],
        fetched_at: r.fetched_at,
      };
      if (!byCity[r.city]) byCity[r.city] = [];
      byCity[r.city].push(enriched);
    }
    for (const city of Object.keys(byCity)) {
      byCity[city].sort((a, b) => b.lifestyle_composite - a.lifestyle_composite);
    }

    return NextResponse.json({ cities: byCity });
  } catch (err) {
    console.error('[av-lifestyle] Failed to read lifestyle data:', err?.message || err);
    return NextResponse.json({ error: 'Could not load lifestyle data' }, { status: 500 });
  }
}
